// Radius UI Framework - Icons/IconSet.Anatomy.cs
// GENERATED by _dev/RadiusUIFramework/texture-intake/gen_iconset.sh - do not hand-edit.
// TIER 2 - rendered illustrations with baked shading. NEVER hue-tinted; alpha only.

namespace RadiusUI.Framework
{
    public static partial class IconSet
    {
        /// <summary>Bone and organ illustrations. Tier 2: shaded beige art. RadiusIcon.Draw reduces any requested tint to its alpha for these, so a caller cannot wash them with an accent colour even by accident.</summary>
        public static class Anatomy
        {
            public static readonly RadiusIcon Bone_Clavicle = Reg("Anatomy/Bone_Clavicle", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Femur = Reg("Anatomy/Bone_Femur", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Foot = Reg("Anatomy/Bone_Foot", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Forearm = Reg("Anatomy/Bone_Forearm", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Generic = Reg("Anatomy/Bone_Generic", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Hand = Reg("Anatomy/Bone_Hand", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Humerus = Reg("Anatomy/Bone_Humerus", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Jaw = Reg("Anatomy/Bone_Jaw", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Neck = Reg("Anatomy/Bone_Neck", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Pelvis = Reg("Anatomy/Bone_Pelvis", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Ribcage = Reg("Anatomy/Bone_Ribcage", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Scapula = Reg("Anatomy/Bone_Scapula", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Shin = Reg("Anatomy/Bone_Shin", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Skull = Reg("Anatomy/Bone_Skull", IconTier.Illustration);
            public static readonly RadiusIcon Bone_Spine = Reg("Anatomy/Bone_Spine", IconTier.Illustration);
            public static readonly RadiusIcon Organ_Brain = Reg("Anatomy/Organ_Brain", IconTier.Illustration);
            public static readonly RadiusIcon Organ_Eye = Reg("Anatomy/Organ_Eye", IconTier.Illustration);
            public static readonly RadiusIcon Organ_Generic = Reg("Anatomy/Organ_Generic", IconTier.Illustration);
            public static readonly RadiusIcon Organ_Heart = Reg("Anatomy/Organ_Heart", IconTier.Illustration);
            public static readonly RadiusIcon Organ_Kidney = Reg("Anatomy/Organ_Kidney", IconTier.Illustration);
            public static readonly RadiusIcon Organ_LargeIntestine = Reg("Anatomy/Organ_LargeIntestine", IconTier.Illustration);
            public static readonly RadiusIcon Organ_Liver = Reg("Anatomy/Organ_Liver", IconTier.Illustration);
            public static readonly RadiusIcon Organ_Lung = Reg("Anatomy/Organ_Lung", IconTier.Illustration);
            public static readonly RadiusIcon Organ_SmallIntestine = Reg("Anatomy/Organ_SmallIntestine", IconTier.Illustration);
            public static readonly RadiusIcon Organ_Stomach = Reg("Anatomy/Organ_Stomach", IconTier.Illustration);
        }

    }
}
