// Radius UI Framework - Icons/IconSet.Glyphs.cs
// GENERATED by _dev/RadiusUIFramework/texture-intake/gen_iconset.sh - do not hand-edit.
// TIER 1 - flat-white glyphs. All information is in the alpha channel, so these tint freely.

namespace RadiusUI.Framework
{
    public static partial class IconSet
    {
        /// <summary>Verbs and controls the player triggers.</summary>
        public static class Action
        {
            public static readonly RadiusIcon Accept = Reg("Action/Accept", IconTier.Glyph);
            public static readonly RadiusIcon AcceptFor = Reg("Action/AcceptFor", IconTier.Glyph);
            public static readonly RadiusIcon Apparel = Reg("Action/Apparel", IconTier.Glyph);
            public static readonly RadiusIcon Bio = Reg("Action/Bio", IconTier.Glyph);
            public static readonly RadiusIcon Check = Reg("Action/Check", IconTier.Glyph);
            public static readonly RadiusIcon ChevronDown = Reg("Action/ChevronDown", IconTier.Glyph);
            public static readonly RadiusIcon CommandCenter = Reg("Action/CommandCenter", IconTier.Glyph);
            public static readonly RadiusIcon CursorDrop = Reg("Action/CursorDrop", IconTier.Glyph);
            public static readonly RadiusIcon CursorGrab = Reg("Action/CursorGrab", IconTier.Glyph);
            public static readonly RadiusIcon Decline = Reg("Action/Decline", IconTier.Glyph);
            public static readonly RadiusIcon DefPos = Reg("Action/DefPos", IconTier.Glyph);
            public static readonly RadiusIcon DevEye = Reg("Action/DevEye", IconTier.Glyph);
            public static readonly RadiusIcon DevPlus = Reg("Action/DevPlus", IconTier.Glyph);
            public static readonly RadiusIcon DevTrash = Reg("Action/DevTrash", IconTier.Glyph);
            public static readonly RadiusIcon Dock = Reg("Action/Dock", IconTier.Glyph);
            public static readonly RadiusIcon Draft = Reg("Action/Draft", IconTier.Glyph);
            public static readonly RadiusIcon EyeClosed = Reg("Action/EyeClosed", IconTier.Glyph);
            public static readonly RadiusIcon EyeClosedBar = Reg("Action/EyeClosedBar", IconTier.Glyph);
            public static readonly RadiusIcon EyeOpen = Reg("Action/EyeOpen", IconTier.Glyph);
            public static readonly RadiusIcon EyeOpenBar = Reg("Action/EyeOpenBar", IconTier.Glyph);
            public static readonly RadiusIcon Fast1 = Reg("Action/Fast1", IconTier.Glyph);
            public static readonly RadiusIcon Fast2 = Reg("Action/Fast2", IconTier.Glyph);
            public static readonly RadiusIcon Fast3 = Reg("Action/Fast3", IconTier.Glyph);
            public static readonly RadiusIcon Grid = Reg("Action/Grid", IconTier.Glyph);
            public static readonly RadiusIcon Jump = Reg("Action/Jump", IconTier.Glyph);
            public static readonly RadiusIcon LockClosed = Reg("Action/LockClosed", IconTier.Glyph);
            public static readonly RadiusIcon LockOpen = Reg("Action/LockOpen", IconTier.Glyph);
            public static readonly RadiusIcon Next = Reg("Action/Next", IconTier.Glyph);
            public static readonly RadiusIcon Pin = Reg("Action/Pin", IconTier.Glyph);
            public static readonly RadiusIcon PinQuest = Reg("Action/PinQuest", IconTier.Glyph);
            public static readonly RadiusIcon Play = Reg("Action/Play", IconTier.Glyph);
            public static readonly RadiusIcon Policies = Reg("Action/Policies", IconTier.Glyph);
            public static readonly RadiusIcon Popout = Reg("Action/Popout", IconTier.Glyph);
            public static readonly RadiusIcon Prev = Reg("Action/Prev", IconTier.Glyph);
            public static readonly RadiusIcon Rename = Reg("Action/Rename", IconTier.Glyph);
            public static readonly RadiusIcon Resume = Reg("Action/Resume", IconTier.Glyph);
            public static readonly RadiusIcon Settings = Reg("Action/Settings", IconTier.Glyph);
            public static readonly RadiusIcon Snooze = Reg("Action/Snooze", IconTier.Glyph);
            public static readonly RadiusIcon Social = Reg("Action/Social", IconTier.Glyph);
            public static readonly RadiusIcon Strip = Reg("Action/Strip", IconTier.Glyph);
            public static readonly RadiusIcon StripArrow = Reg("Action/StripArrow", IconTier.Glyph);
            public static readonly RadiusIcon Swap = Reg("Action/Swap", IconTier.Glyph);
            public static readonly RadiusIcon SwapStat = Reg("Action/SwapStat", IconTier.Glyph);
            public static readonly RadiusIcon SwapView = Reg("Action/SwapView", IconTier.Glyph);
            public static readonly RadiusIcon TabArmory = Reg("Action/TabArmory", IconTier.Glyph);
            public static readonly RadiusIcon TabStats = Reg("Action/TabStats", IconTier.Glyph);
            public static readonly RadiusIcon ViewBones = Reg("Action/ViewBones", IconTier.Glyph);
            public static readonly RadiusIcon Volume = Reg("Action/Volume", IconTier.Glyph);
            public static readonly RadiusIcon Xray = Reg("Action/Xray", IconTier.Glyph);
        }

        /// <summary>Severity markers.</summary>
        public static class Alert
        {
            public static readonly RadiusIcon Cold = Reg("Alert/Cold", IconTier.Glyph);
            public static readonly RadiusIcon Crit = Reg("Alert/Crit", IconTier.Glyph);
            public static readonly RadiusIcon Info = Reg("Alert/Info", IconTier.Glyph);
            public static readonly RadiusIcon Notice = Reg("Alert/Notice", IconTier.Glyph);
            public static readonly RadiusIcon Threat = Reg("Alert/Threat", IconTier.Glyph);
            public static readonly RadiusIcon Warn = Reg("Alert/Warn", IconTier.Glyph);
            public static readonly RadiusIcon Warning = Reg("Alert/Warning", IconTier.Glyph);
        }

        /// <summary>Non-icon UI shapes - bubble parts, socket, snips.</summary>
        public static class Chrome
        {
            public static readonly RadiusIcon Bubble = Reg("Chrome/Bubble", IconTier.Glyph);
            public static readonly RadiusIcon Bubble_Edge = Reg("Chrome/Bubble_Edge", IconTier.Glyph);
            public static readonly RadiusIcon Bubble_Tail = Reg("Chrome/Bubble_Tail", IconTier.Glyph);
            public static readonly RadiusIcon SnipEvent = Reg("Chrome/SnipEvent", IconTier.Glyph);
            public static readonly RadiusIcon SnipMove = Reg("Chrome/SnipMove", IconTier.Glyph);
            public static readonly RadiusIcon SnipQuest = Reg("Chrome/SnipQuest", IconTier.Glyph);
            public static readonly RadiusIcon SnipRelic = Reg("Chrome/SnipRelic", IconTier.Glyph);
            public static readonly RadiusIcon SnipTitle = Reg("Chrome/SnipTitle", IconTier.Glyph);
            public static readonly RadiusIcon Socket = Reg("Chrome/Socket", IconTier.Glyph);
        }

        /// <summary>Universal nouns.</summary>
        public static class Common
        {
            public static readonly RadiusIcon Bell = Reg("Common/Bell", IconTier.Glyph);
            public static readonly RadiusIcon Book = Reg("Common/Book", IconTier.Glyph);
            public static readonly RadiusIcon BookClosed = Reg("Common/BookClosed", IconTier.Glyph);
            public static readonly RadiusIcon BookOpen = Reg("Common/BookOpen", IconTier.Glyph);
            public static readonly RadiusIcon Cal = Reg("Common/Cal", IconTier.Glyph);
            public static readonly RadiusIcon Chest = Reg("Common/Chest", IconTier.Glyph);
            public static readonly RadiusIcon Clock = Reg("Common/Clock", IconTier.Glyph);
            public static readonly RadiusIcon Fang = Reg("Common/Fang", IconTier.Glyph);
            public static readonly RadiusIcon Heart = Reg("Common/Heart", IconTier.Glyph);
            public static readonly RadiusIcon Leaf = Reg("Common/Leaf", IconTier.Glyph);
            public static readonly RadiusIcon Letter = Reg("Common/Letter", IconTier.Glyph);
            public static readonly RadiusIcon Mail = Reg("Common/Mail", IconTier.Glyph);
            public static readonly RadiusIcon Note = Reg("Common/Note", IconTier.Glyph);
            public static readonly RadiusIcon Pod = Reg("Common/Pod", IconTier.Glyph);
            public static readonly RadiusIcon Scroll = Reg("Common/Scroll", IconTier.Glyph);
            public static readonly RadiusIcon Skull = Reg("Common/Skull", IconTier.Glyph);
            public static readonly RadiusIcon Sword = Reg("Common/Sword", IconTier.Glyph);
        }

        /// <summary>Game conditions and environmental hazards.</summary>
        public static class Condition
        {
            public static readonly RadiusIcon Ash = Reg("Condition/Ash", IconTier.Glyph);
            public static readonly RadiusIcon Aurora = Reg("Condition/Aurora", IconTier.Glyph);
            public static readonly RadiusIcon Drought = Reg("Condition/Drought", IconTier.Glyph);
            public static readonly RadiusIcon EMI = Reg("Condition/EMI", IconTier.Glyph);
            public static readonly RadiusIcon Eclipse = Reg("Condition/Eclipse", IconTier.Glyph);
            public static readonly RadiusIcon Eclipse2 = Reg("Condition/Eclipse2", IconTier.Glyph);
            public static readonly RadiusIcon Fauna = Reg("Condition/Fauna", IconTier.Glyph);
            public static readonly RadiusIcon Fire = Reg("Condition/Fire", IconTier.Glyph);
            public static readonly RadiusIcon Gravity = Reg("Condition/Gravity", IconTier.Glyph);
            public static readonly RadiusIcon Mech = Reg("Condition/Mech", IconTier.Glyph);
            public static readonly RadiusIcon Moon = Reg("Condition/Moon", IconTier.Glyph);
            public static readonly RadiusIcon Plague = Reg("Condition/Plague", IconTier.Glyph);
            public static readonly RadiusIcon Planetkiller = Reg("Condition/Planetkiller", IconTier.Glyph);
            public static readonly RadiusIcon Psychic = Reg("Condition/Psychic", IconTier.Glyph);
            public static readonly RadiusIcon Quake = Reg("Condition/Quake", IconTier.Glyph);
            public static readonly RadiusIcon Radiation = Reg("Condition/Radiation", IconTier.Glyph);
            public static readonly RadiusIcon Rainbow = Reg("Condition/Rainbow", IconTier.Glyph);
            public static readonly RadiusIcon Skull = Reg("Condition/Skull", IconTier.Glyph);
            public static readonly RadiusIcon SolarFlare = Reg("Condition/SolarFlare", IconTier.Glyph);
            public static readonly RadiusIcon Telescope = Reg("Condition/Telescope", IconTier.Glyph);
            public static readonly RadiusIcon Toxic = Reg("Condition/Toxic", IconTier.Glyph);
            public static readonly RadiusIcon Volcano = Reg("Condition/Volcano", IconTier.Glyph);
        }

        /// <summary>Incidents and arrivals.</summary>
        public static class Event
        {
            public static readonly RadiusIcon Bug = Reg("Event/Bug", IconTier.Glyph);
            public static readonly RadiusIcon Disease = Reg("Event/Disease", IconTier.Glyph);
            public static readonly RadiusIcon Joiner = Reg("Event/Joiner", IconTier.Glyph);
            public static readonly RadiusIcon Pod = Reg("Event/Pod", IconTier.Glyph);
            public static readonly RadiusIcon Quest = Reg("Event/Quest", IconTier.Glyph);
            public static readonly RadiusIcon Raid = Reg("Event/Raid", IconTier.Glyph);
            public static readonly RadiusIcon Trade = Reg("Event/Trade", IconTier.Glyph);
            public static readonly RadiusIcon Visitor = Reg("Event/Visitor", IconTier.Glyph);
        }

        /// <summary>Health-domain nouns.</summary>
        public static class Medical
        {
            public static readonly RadiusIcon Bandage = Reg("Medical/Bandage", IconTier.Glyph);
            public static readonly RadiusIcon Bionic = Reg("Medical/Bionic", IconTier.Glyph);
            public static readonly RadiusIcon Bleed = Reg("Medical/Bleed", IconTier.Glyph);
            public static readonly RadiusIcon Illness = Reg("Medical/Illness", IconTier.Glyph);
            public static readonly RadiusIcon Injury = Reg("Medical/Injury", IconTier.Glyph);
            public static readonly RadiusIcon Missing = Reg("Medical/Missing", IconTier.Glyph);
            public static readonly RadiusIcon Pain = Reg("Medical/Pain", IconTier.Glyph);
            public static readonly RadiusIcon Surgery = Reg("Medical/Surgery", IconTier.Glyph);
        }

        /// <summary>Calendar and social occasions.</summary>
        public static class Occasion
        {
            public static readonly RadiusIcon Anniversary = Reg("Occasion/Anniversary", IconTier.Glyph);
            public static readonly RadiusIcon Appointment = Reg("Occasion/Appointment", IconTier.Glyph);
            public static readonly RadiusIcon Birthday = Reg("Occasion/Birthday", IconTier.Glyph);
            public static readonly RadiusIcon Caravan = Reg("Occasion/Caravan", IconTier.Glyph);
            public static readonly RadiusIcon Challenge = Reg("Occasion/Challenge", IconTier.Glyph);
            public static readonly RadiusIcon Conclave = Reg("Occasion/Conclave", IconTier.Glyph);
            public static readonly RadiusIcon Coronation = Reg("Occasion/Coronation", IconTier.Glyph);
            public static readonly RadiusIcon Death = Reg("Occasion/Death", IconTier.Glyph);
            public static readonly RadiusIcon Election = Reg("Occasion/Election", IconTier.Glyph);
            public static readonly RadiusIcon Growth = Reg("Occasion/Growth", IconTier.Glyph);
            public static readonly RadiusIcon Marriage = Reg("Occasion/Marriage", IconTier.Glyph);
            public static readonly RadiusIcon Milestone = Reg("Occasion/Milestone", IconTier.Glyph);
            public static readonly RadiusIcon Pregnancy = Reg("Occasion/Pregnancy", IconTier.Glyph);
            public static readonly RadiusIcon Reminder = Reg("Occasion/Reminder", IconTier.Glyph);
            public static readonly RadiusIcon Research = Reg("Occasion/Research", IconTier.Glyph);
            public static readonly RadiusIcon Ritual = Reg("Occasion/Ritual", IconTier.Glyph);
            public static readonly RadiusIcon Royal = Reg("Occasion/Royal", IconTier.Glyph);
            public static readonly RadiusIcon Shuttle = Reg("Occasion/Shuttle", IconTier.Glyph);
        }

        /// <summary>The reminder-picker palette. 7 files; the 8th slot is an alias - see ReminderSlots.</summary>
        public static class Reminder
        {
            public static readonly RadiusIcon Alert = Reg("Reminder/Alert", IconTier.Glyph);
            public static readonly RadiusIcon Bell = Reg("Reminder/Bell", IconTier.Glyph);
            public static readonly RadiusIcon Check = Reg("Reminder/Check", IconTier.Glyph);
            public static readonly RadiusIcon Clock = Reg("Reminder/Clock", IconTier.Glyph);
            public static readonly RadiusIcon Flag = Reg("Reminder/Flag", IconTier.Glyph);
            public static readonly RadiusIcon Gift = Reg("Reminder/Gift", IconTier.Glyph);
            public static readonly RadiusIcon Heart = Reg("Reminder/Heart", IconTier.Glyph);
        }

        /// <summary>Ordered set - see Seasons.</summary>
        public static class Season
        {
            public static readonly RadiusIcon Fall = Reg("Season/Fall", IconTier.Glyph);
            public static readonly RadiusIcon PermanentSummer = Reg("Season/PermanentSummer", IconTier.Glyph);
            public static readonly RadiusIcon PermanentWinter = Reg("Season/PermanentWinter", IconTier.Glyph);
            public static readonly RadiusIcon Spring = Reg("Season/Spring", IconTier.Glyph);
            public static readonly RadiusIcon Summer = Reg("Season/Summer", IconTier.Glyph);
            public static readonly RadiusIcon Winter = Reg("Season/Winter", IconTier.Glyph);
        }

        /// <summary>Equipment and apparel slots.</summary>
        public static class Slot
        {
            public static readonly RadiusIcon Amulet = Reg("Slot/Amulet", IconTier.Glyph);
            public static readonly RadiusIcon Belt = Reg("Slot/Belt", IconTier.Glyph);
            public static readonly RadiusIcon Boots = Reg("Slot/Boots", IconTier.Glyph);
            public static readonly RadiusIcon Cape = Reg("Slot/Cape", IconTier.Glyph);
            public static readonly RadiusIcon Ears = Reg("Slot/Ears", IconTier.Glyph);
            public static readonly RadiusIcon Eyes = Reg("Slot/Eyes", IconTier.Glyph);
            public static readonly RadiusIcon Gloves = Reg("Slot/Gloves", IconTier.Glyph);
            public static readonly RadiusIcon Helm = Reg("Slot/Helm", IconTier.Glyph);
            public static readonly RadiusIcon Legs = Reg("Slot/Legs", IconTier.Glyph);
            public static readonly RadiusIcon Middle = Reg("Slot/Middle", IconTier.Glyph);
            public static readonly RadiusIcon Pack = Reg("Slot/Pack", IconTier.Glyph);
            public static readonly RadiusIcon Ring = Reg("Slot/Ring", IconTier.Glyph);
            public static readonly RadiusIcon Shirt = Reg("Slot/Shirt", IconTier.Glyph);
            public static readonly RadiusIcon Torso = Reg("Slot/Torso", IconTier.Glyph);
            public static readonly RadiusIcon Utility = Reg("Slot/Utility", IconTier.Glyph);
            public static readonly RadiusIcon Weapon = Reg("Slot/Weapon", IconTier.Glyph);
        }

        /// <summary>Ordered set, indexed by TimeSpeed - see Speeds.</summary>
        public static class Speed
        {
            public static readonly RadiusIcon Fast = Reg("Speed/Fast", IconTier.Glyph);
            public static readonly RadiusIcon Normal = Reg("Speed/Normal", IconTier.Glyph);
            public static readonly RadiusIcon Pause = Reg("Speed/Pause", IconTier.Glyph);
            public static readonly RadiusIcon Superfast = Reg("Speed/Superfast", IconTier.Glyph);
            public static readonly RadiusIcon Ultrafast = Reg("Speed/Ultrafast", IconTier.Glyph);
        }

        /// <summary>Ordered set. 5 files; 3 more slots are aliases - see SquadEmblems.</summary>
        public static class Squad
        {
            public static readonly RadiusIcon Icon0 = Reg("Squad/Icon0", IconTier.Glyph);
            public static readonly RadiusIcon Icon1 = Reg("Squad/Icon1", IconTier.Glyph);
            public static readonly RadiusIcon Icon2 = Reg("Squad/Icon2", IconTier.Glyph);
            public static readonly RadiusIcon Icon5 = Reg("Squad/Icon5", IconTier.Glyph);
            public static readonly RadiusIcon Icon6 = Reg("Squad/Icon6", IconTier.Glyph);
        }

        /// <summary>Stat and attribute glyphs.</summary>
        public static class Stat
        {
            public static readonly RadiusIcon BarGraph = Reg("Stat/BarGraph", IconTier.Glyph);
            public static readonly RadiusIcon Blunt = Reg("Stat/Blunt", IconTier.Glyph);
            public static readonly RadiusIcon Box = Reg("Stat/Box", IconTier.Glyph);
            public static readonly RadiusIcon Bullet = Reg("Stat/Bullet", IconTier.Glyph);
            public static readonly RadiusIcon Chevron = Reg("Stat/Chevron", IconTier.Glyph);
            public static readonly RadiusIcon Cross = Reg("Stat/Cross", IconTier.Glyph);
            public static readonly RadiusIcon Droplet = Reg("Stat/Droplet", IconTier.Glyph);
            public static readonly RadiusIcon Fist = Reg("Stat/Fist", IconTier.Glyph);
            public static readonly RadiusIcon Flame = Reg("Stat/Flame", IconTier.Glyph);
            public static readonly RadiusIcon Food = Reg("Stat/Food", IconTier.Glyph);
            public static readonly RadiusIcon Fps = Reg("Stat/Fps", IconTier.Glyph);
            public static readonly RadiusIcon Glow = Reg("Stat/Glow", IconTier.Glyph);
            public static readonly RadiusIcon Heart = Reg("Stat/Heart", IconTier.Glyph);
            public static readonly RadiusIcon Heat = Reg("Stat/Heat", IconTier.Glyph);
            public static readonly RadiusIcon Melee = Reg("Stat/Melee", IconTier.Glyph);
            public static readonly RadiusIcon Mood = Reg("Stat/Mood", IconTier.Glyph);
            public static readonly RadiusIcon Quality = Reg("Stat/Quality", IconTier.Glyph);
            public static readonly RadiusIcon Sharp = Reg("Stat/Sharp", IconTier.Glyph);
            public static readonly RadiusIcon Shield = Reg("Stat/Shield", IconTier.Glyph);
            public static readonly RadiusIcon Shooting = Reg("Stat/Shooting", IconTier.Glyph);
            public static readonly RadiusIcon Skull = Reg("Stat/Skull", IconTier.Glyph);
            public static readonly RadiusIcon Speech = Reg("Stat/Speech", IconTier.Glyph);
            public static readonly RadiusIcon Temp = Reg("Stat/Temp", IconTier.Glyph);
            public static readonly RadiusIcon Temperature = Reg("Stat/Temperature", IconTier.Glyph);
            public static readonly RadiusIcon Tetris = Reg("Stat/Tetris", IconTier.Glyph);
            public static readonly RadiusIcon Thermometer = Reg("Stat/Thermometer", IconTier.Glyph);
            public static readonly RadiusIcon TrendDown = Reg("Stat/TrendDown", IconTier.Glyph);
            public static readonly RadiusIcon TrendFlat = Reg("Stat/TrendFlat", IconTier.Glyph);
            public static readonly RadiusIcon TrendUp = Reg("Stat/TrendUp", IconTier.Glyph);
            public static readonly RadiusIcon Wave = Reg("Stat/Wave", IconTier.Glyph);
            public static readonly RadiusIcon Wealth = Reg("Stat/Wealth", IconTier.Glyph);
            public static readonly RadiusIcon Weight = Reg("Stat/Weight", IconTier.Glyph);
        }

        /// <summary>Pawn state badges.</summary>
        public static class Status
        {
            public static readonly RadiusIcon Aim = Reg("Status/Aim", IconTier.Glyph);
            public static readonly RadiusIcon Break = Reg("Status/Break", IconTier.Glyph);
            public static readonly RadiusIcon Burning = Reg("Status/Burning", IconTier.Glyph);
            public static readonly RadiusIcon Caravan = Reg("Status/Caravan", IconTier.Glyph);
            public static readonly RadiusIcon Danger = Reg("Status/Danger", IconTier.Glyph);
            public static readonly RadiusIcon Flee = Reg("Status/Flee", IconTier.Glyph);
            public static readonly RadiusIcon Focus = Reg("Status/Focus", IconTier.Glyph);
            public static readonly RadiusIcon Idle = Reg("Status/Idle", IconTier.Glyph);
            public static readonly RadiusIcon Inspired = Reg("Status/Inspired", IconTier.Glyph);
            public static readonly RadiusIcon Medical = Reg("Status/Medical", IconTier.Glyph);
            public static readonly RadiusIcon Mount = Reg("Status/Mount", IconTier.Glyph);
            public static readonly RadiusIcon Research = Reg("Status/Research", IconTier.Glyph);
            public static readonly RadiusIcon Zzz = Reg("Status/Zzz", IconTier.Glyph);
        }

        /// <summary>Weather states.</summary>
        public static class Weather
        {
            public static readonly RadiusIcon Anomaly = Reg("Weather/Anomaly", IconTier.Glyph);
            public static readonly RadiusIcon Clear = Reg("Weather/Clear", IconTier.Glyph);
            public static readonly RadiusIcon Fog = Reg("Weather/Fog", IconTier.Glyph);
            public static readonly RadiusIcon HeavyRain = Reg("Weather/HeavyRain", IconTier.Glyph);
            public static readonly RadiusIcon Moon = Reg("Weather/Moon", IconTier.Glyph);
            public static readonly RadiusIcon Overcast = Reg("Weather/Overcast", IconTier.Glyph);
            public static readonly RadiusIcon Rain = Reg("Weather/Rain", IconTier.Glyph);
            public static readonly RadiusIcon Rain2 = Reg("Weather/Rain2", IconTier.Glyph);
            public static readonly RadiusIcon Sandstorm = Reg("Weather/Sandstorm", IconTier.Glyph);
            public static readonly RadiusIcon Sun = Reg("Weather/Sun", IconTier.Glyph);
            public static readonly RadiusIcon Thunder = Reg("Weather/Thunder", IconTier.Glyph);
            public static readonly RadiusIcon Wind = Reg("Weather/Wind", IconTier.Glyph);
            public static readonly RadiusIcon Wind2 = Reg("Weather/Wind2", IconTier.Glyph);
        }

    }
}
