// Radius UI Framework - Icons/IconSet.Marker.cs
// GENERATED by _dev/RadiusUIFramework/texture-intake/gen_iconset.sh - do not hand-edit.
// TIER 3 - semantic markers whose baked colour IS their meaning. Alpha only.

namespace RadiusUI.Framework
{
    public static partial class IconSet
    {
        /// <summary>Semantic decals. Their colours mirror the Palette.Health marker ramp and are baked into the PNGs; if that ramp changes these 8 files must be re-authored by hand.</summary>
        public static class Marker
        {
            public static readonly RadiusIcon Bandage = Reg("Marker/Bandage", IconTier.Marker);
            public static readonly RadiusIcon Blood = Reg("Marker/Blood", IconTier.Marker);
            public static readonly RadiusIcon Burn = Reg("Marker/Burn", IconTier.Marker);
            public static readonly RadiusIcon Chronic = Reg("Marker/Chronic", IconTier.Marker);
            public static readonly RadiusIcon Frost = Reg("Marker/Frost", IconTier.Marker);
            public static readonly RadiusIcon Missing = Reg("Marker/Missing", IconTier.Marker);
            public static readonly RadiusIcon Toxic = Reg("Marker/Toxic", IconTier.Marker);
            public static readonly RadiusIcon Virus = Reg("Marker/Virus", IconTier.Marker);
        }

    }
}
